version: "3.8"

services:
  followers_service:
    image: followers_service
    container_name: followers_service
    build:
      context: .
      dockerfile: ./Followers_microservice/Dockerfile
    restart: on-failure
    environment:
      FOLLOWERS_SERVICE_PORT: ${FOLLOWERS_SERVICE_PORT}
    networks:
      - network
            
  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      FOLLOWERS_SERVICE_HOST: ${FOLLOWERS_SERVICE_HOST}
      FOLLOWERS_SERVICE_PORT: ${FOLLOWERS_SERVICE_PORT}
    networks:
      - network
      
networks:
  network:
    driver: bridge